version: '2'

services:
  app:
    build: .
    ports:
      - "3005:3000"
    expose:
      - "3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - MYSQL_HOST=database  # Changed from localhost to database
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=ThisIsAStrongPassword
      - MYSQL_DB=TaskUpDB
      - MYSQL_USER_TABLE=Users
      - MYSQL_TASK_TABLE=TaskList
    restart: always

  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=TaskUpDB
      - MYSQL_ROOT_PASSWORD=ThisIsAStrongPassword
    volumes:
      - task-up-data:/var/lib/mysql

volumes:
  task-up-data:
