version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - DATABASE_URL=https://taskup-tnav-default-rtdb.firebaseio.com
    restart: always

volumes:
  data:
